artifactory:
  userPluginSecrets:
    - admin-password-plugin
  customVolumeMounts: |
    - name: artifactory-license
      mountPath: "/artifactory_extra_conf/admin.password"
      subPath: admin.password
